#!/bin/bash

function link_dotfiles {
  DIRPATH="${PWD}/${1}/*"
  for FILE in $DIRPATH; do
    link_file $FILE
  done;
}

function link_file {
  FILEPATH=$1
  FILE=$(basename "$FILEPATH")
  echo "linking $FILE"
  if [[ -f "${HOME}/.${FILE}" ]]; then
    rm "${HOME}/.${FILE}"
  fi
  ln -s ${FILEPATH} ${HOME}/.${FILE}
}

function config_gitignore {
  git config --global core.excludesfile ~/.gitignore
}

function install_brew {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

function brew_install_casks {
  CASKS=(
    1password
    appcleaner
    arq
    brave-browser
    fzf
    iterm2
    google-chrome
    postman
    rectangle
    spotify
  )

  for PACKAGE in ${CASKS[@]}
  do
    brew install --cask $PACKAGE
    if [ $? -eq 0 ]; then
      echo "$PACKAGE installed"
    else
      echo "$PACKAGE not installed"
    fi
  done
}

function brew_install_packages {
  PACKAGES=(
    ctags
    fzf
    node
    postgresql
    ripgrep
    yarn
  )

  for PACKAGE in ${PACKAGES[@]}
  do
    brew install $PACKAGE
    if [ $? -eq 0 ]; then
      echo "$PACKAGE installed"
    else
      echo "$PACKAGE not installed"
    fi
  done
}

function brew_install {
  brew_install_packages
  brew_install_casks
}

function install_vim_plug {
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

function npm_install {
  npm install --global git-open
}

function default_setup {
  link_dotfiles "config"
  config_gitignore
  install_brew
  brew_install
  install_vim_plug
  npm_install
}

function codespaces_setup {
  link_dotfiles "config"
  config_gitignore
  install_vim_plug
}

function setup {
  if [[ $CODESPACES ]]; then
    codespaces_setup
  else
    default_setup
  fi
}

setup
