# NIKYMORG BASH PROFILE
# =====================

# Sourcing files
if [[ $CODESPACES ]]; then
  for file in /workspaces/.codespaces/.persistedshare/dotfiles/scripts/*; do
	  [ -r "$file" ] && [ -f "$file" ] && source "$file";
  done;
  echo "Welcome to your codespace! ✨"
else
  for file in ~/.dotfiles/scripts/*; do
	  [ -r "$file" ] && [ -f "$file" ] && source "$file";
  done;
fi

bash_prompt
