# Sourcing files
if [[ $CODESPACES ]]; then
  # Source common scripts
  for file in /workspaces/.codespaces/.persistedshare/dotfiles/scripts/common/*.sh; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
  done;
  
  echo "Welcome to your codespace! ✨"
else
  # Source common scripts
  for file in ~/.dotfiles/scripts/common/*.sh; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
  done;
  
  # Source macOS-specific scripts
  for file in ~/.dotfiles/scripts/macos/*.sh; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
  done;
fi

bash_prompt

# Initialize Homebrew
if command -v brew &> /dev/null; then
  eval "$(brew shellenv)"
fi
