# Brewfile

tap "homebrew/bundle"
tap "homebrew/cask"
tap "universal-ctags/universal-ctags"

brew "ripgrep"
brew "tmux"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

if OS.mac?
  brew "gh", args: ["HEAD"]
  brew "git"
  brew "jq"
  brew "node@14"
  brew "ripgrep"
  brew "yarn"

  cask "1password"
  cask "appcleaner"
  cask "arq"
  cask "brave-browser"
  cask "google-chrome"
  cask "graphiql"
  cask "iterm2"
  cask "jumpcut"
  cask "macdown"
  cask "postman"
  cask "rectangle"
  cask "spotify"
end
