# Brewfile

tap "homebrew/bundle"
tap "homebrew/cask"

brew "neovim" unless system "/usr/bin/nvim --failfast"
brew "fzf"
brew "ripgrep"
brew "tmux" unless system "/usr/bin/tmux --failfast"
brew "universal-ctags"

if OS.mac?
  brew "gh", args: ["HEAD"]
  brew "git"
  brew "jq"
  brew "node@14"
  brew "ripgrep"
  brew "yarn"

  cask "1password"
  cask "appcleaner"
  cask "arq"
  cask "brave-browser"
  cask "google-chrome"
  cask "graphiql"
  cask "iterm2"
  cask "jumpcut"
  cask "macdown"
  cask "rectangle"
  cask "spotify"
end
