# load prompt
if [[ $CODESPACES ]]; then
  FILE="/workspaces/.codespaces/.persistedshare/dotfiles/scripts/prompts.sh"
  [ -r "$FILE" ] && [ -f "$FILE" ] && source "$FILE"
fi;
zsh_prompt

if type rg &> /dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files'
  export FZF_DEFAULT_OPTS='-m --height 50% --border'
fi
